### ISSUE TITLE
Import error for  'RPLogger' and RPLogHandler after update to 5.1.0

### ISSUE THREAD

**Issue by dkuchynskyi** [reportportal/agent-python-pytest#303]
Hi!

selenium==4.1.3
pytest == 7.1.1
pytest-reportportal==5.1.0

After updating to the latest version of pytest report portal (5.1.0) error appears:

  ImportError: cannot import name 'RPLogger' from 'pytest_reportportal' 

thanks!

**Comment by lolrenx** [comment]
same error here using pylenium (having report portal as dependency) 
**conftest.py:15: in <module>
    from pytest_reportportal import RPLogger, RPLogHandler
E   ImportError: cannot import name 'RPLogger' from 'pytest_reportportal' (.../venv/lib/python3.10/site-packages/pytest_reportportal/__init__.py)**

**Comment by lolrenx** [comment]
looks like RPLogger was removed from the file 
https://github.com/reportportal/agent-python-pytest/compare/5.0.12...5.1.0#diff-61c89fa72bfd8818344ac0ce7995fcbdaadc5f0e0861558db7eb4e3f6ff7f3d7

**Comment by HardNorth** [comment]
Yes, it is moved. That's why we changed major version.

**Comment by dkuchynskyi** [comment]
Please update documentation, now it is looks like that:
![image](https://user-images.githubusercontent.com/34566341/163148004-bf35bb84-3595-4619-9cc5-c2f071682007.png)

**Comment by HardNorth** [comment]
@dkuchynskyi Done. Yeah probably not the best decision to move it at once. Will do some transition period with class deprecation next time.

**Comment by rnestler** [comment]
> Yes, it is moved. That's why we changed major version.

Hmm? The major version didn't change. It is still 5.

**Comment by HardNorth** [comment]
Yes, this one version follows server's API changes.
