### ISSUE TITLE
Failed run test with xdist

### ISSUE THREAD

**Issue by ilyubin** [reportportal/agent-python-pytest#108]
*Problem*
Run pytest + xdist with reportportal failed

*How to reproduce?*

I have follow files:

`tests/test_report_portal.py`
```python
def test_RP1():
    assert True


def test_RP2():
    assert False
```

`pytest.ini`

```ini
[pytest]
rp_uuid = 4eb45953-d51d-42a5-9447-8082a24aa516
rp_endpoint = https://my.rp.address.ru
rp_project = my-rp-project
```

Run tests with xdist
```
pytest tests/test_report_portal.py --reportportal -n 3 
```

*Actual result*

```bash
pytest tests/test_report_portal.py --reportportal -n 3         
====================================================================================================== test session starts ======================================================================================================
platform darwin -- Python 3.6.5, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /Users/user/git/myProject, inifile: pytest.ini
plugins: xdist-1.24.1, rerunfailures-4.2, reportportal-1.0.4, forked-1.0.2, allure-pytest-2.3.2b1
gw0 [12] / gw1 [12] / gw2 [12]
scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/_pytest/main.py", line 107, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/_pytest/main.py", line 145, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firsINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/_pytest/main.py", line 107, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/_pytest/main.py", line 145, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 66, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 83, in run_one_test
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 175, in _multicall
INTERNALERROR>     next(gen)   # first yield
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pytest_reportportal/listener.py", line 32, in pytest_runtest_protocol
tresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>     self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pytest_reportportal/service.py", line 194, in start_pytest_item
INTERNALERROR>     part = self._start_stack.pop(0)
INTERNALERROR> IndexError: pop from empty list
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 66, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 83, in run_one_test
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 175, in _multicall
INTERNALERROR>     next(gen)   # first yield
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pytest_reportportal/listener.py", line 32, in pytest_runtest_protocol
INTERNALERROR>     self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pytest_reportportal/service.py", line 194, in start_pytest_item
INTERNALERROR>     part = self._start_stack.pop(0)
INTERNALERROR> IndexError: pop from empty list
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/_pytest/main.py", line 107, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/_pytest/main.py", line 145, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 66, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 83, in run_one_test
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pluggy/callers.py", line 175, in _multicall
INTERNALERROR>     next(gen)   # first yield
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pytest_reportportal/listener.py", line 32, in pytest_runtest_protocol
INTERNALERROR>     self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "/Users/user/git/myProject/qenv/lib/python3.6/site-packages/pytest_reportportal/service.py", line 194, in start_pytest_item
INTERNALERROR>     part = self._start_stack.pop(0)
INTERNALERROR> IndexError: pop from empty list
```

*Expected*

No errors

*PS*

If I run tests sequantely - no errors
```bash
pytest tests/test_report_portal.py --reportportal
```

**Comment by krasoffski** [comment]
There was the similar issue with `xdist` #29 which had been fixed by adding flag for `xdist` initialization. Probably there are some changes with internal implementation of `xdist` and this require investigation.

**Comment by iivanou** [comment]
@ilyubin , @apertureqa Could you confirm that the issue is not reproducible with 1.0.8 version of the agent? 

`# pytest tests/test_report_portal.py --reportportal -n 3 -vv
platform linux -- Python 3.6.5, pytest-4.5.0, py-1.5.3, pluggy-0.11.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
metadata: {'Python': '3.6.5', 'Platform': 'Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-centos-7.6.1810-Core', 'Packages': {'pytest': '4.5.0', 'py': '1.5.3', 'pluggy': '0.11.0'}, 'Plugins': {'xdist': '1.24.1', 'rerunfailures': '5.0', 'reportportal': '1.0.8', 'metadata': '1.7.0', 'lazy-fixture': '0.5.2', 'html': '1.19.0', 'forked': '0.2', 'cov': '2.5.1'}}
rootdir: /root/gerrit/rp_test, inifile: pytest.ini
plugins: xdist-1.24.1, rerunfailures-5.0, reportportal-1.0.8, metadata-1.7.0, lazy-fixture-0.5.2, html-1.19.0, forked-0.2, cov-2.5.1
[gw0] linux Python 3.6.5 cwd: /root/gerrit/rp_test
[gw1] linux Python 3.6.5 cwd: /root/gerrit/rp_test
[gw2] linux Python 3.6.5 cwd: /root/gerrit/rp_test
[gw1] Python 3.6.5 (default, Apr 10 2018, 17:08:37)  -- [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
[gw0] Python 3.6.5 (default, Apr 10 2018, 17:08:37)  -- [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
[gw2] Python 3.6.5 (default, Apr 10 2018, 17:08:37)  -- [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
gw0 [2] / gw1 [2] / gw2 [2]
scheduling tests via LoadScheduling

tests/test_report_portal.py::test_RP1 
[gw1] [ 50%] PASSED tests/test_report_portal.py::test_RP1 
tests/test_report_portal.py::test_RP2 
[gw0] [100%] FAILED tests/test_report_portal.py::test_RP`

**Comment by Abhilash04** [comment]
@iivanou 
I'm using 1.0.8 version and it is still reproducible.
```
platform darwin -- Python 3.7.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.1
rootdir: /Users/Progressio/Documents/Personal/Playground/ReportPortal, inifile: pytest.ini
plugins: reportportal-1.0.8
collected 1 item                                                                                                                                                         

test_report_portal.py 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/_pytest/main.py", line 205, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/_pytest/main.py", line 270, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/_pytest/runner.py", line 77, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/_pytest/runner.py", line 92, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/_pytest/runner.py", line 174, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pytest_reportportal/listener.py", line 78, in pytest_runtest_makereport
INTERNALERROR>     self._add_issue_info(item, report)
INTERNALERROR>   File "/Users/Progressio/Documents/Personal/Playground/ReportPortal/venv/lib/python3.7/site-packages/pytest_reportportal/listener.py", line 115, in _add_issue_info
INTERNALERROR>     if issue_type and self.PyTestService.issue_types \
INTERNALERROR> AttributeError: 'PyTestServiceClass' object has no attribute 'issue_types'
```

**Comment by iivanou** [comment]
@Abhilash04 Are you sure that you put your message into the correct issue? This thread is about issues related to agent failure under the xdist Pytest plugin. You are not using that plugin according to the provided output. The resolution for your failure should have been fixed in #147. Please confirm that.

**Comment by Abhilash04** [comment]
@iivanou I'm not facing this issue anymore. This wasn't related to xdist. Sorry to post on wrong thread.

**Comment by iivanou** [comment]
Closed as can't reproduce with the latest Pytest versions.
